### PR TITLE
fix: Update ACL to fix bucket creation issue

### PR DESCRIPTION
**Pull request by kakakakakku**
Hi😀

I encountered some errors while following the tutorial "Build and Use a Local Module".

- https://developer.hashicorp.com/terraform/tutorials/certification-associate-tutorials-003/module-create

```
╷
│ Error: error creating S3 bucket ACL for robin-test-dec-17-2019-12345: AccessDenied: Access Denied
│       status code: 403, request id: Q215SR0AT6MH119A, host id: MB+OrDPUEJ0BM7WUp6BfimBqUZ9SIfg6/JRDJJTWF4QSUPOqIZBLIrgNngxPsaPa/PFRUp5MtrnmNvrWtfQhtw==
│ 
│   with module.website_s3_bucket.aws_s3_bucket_acl.s3_bucket,
│   on modules/aws-s3-static-website-bucket/main.tf line 24, in resource "aws_s3_bucket_acl" "s3_bucket":
│   24: resource "aws_s3_bucket_acl" "s3_bucket" {
│ 
╵
╷
│ Error: Error putting S3 policy: AccessDenied: Access Denied
│       status code: 403, request id: Q213CRTVSN7QP8MT, host id: W5Qyezt/2RUEmVvbrR7DEFqZXiOiGg9C8ItAb+QNGnWPk6yuASqnTR+WdXEzZ5mkW5LCp6V7Tj/2WEvWd6gGpQ==
│ 
│   with module.website_s3_bucket.aws_s3_bucket_policy.s3_bucket,
│   on modules/aws-s3-static-website-bucket/main.tf line 30, in resource "aws_s3_bucket_policy" "s3_bucket":
│   30: resource "aws_s3_bucket_policy" "s3_bucket" {
│ 
╵
```

I believe this error is a result of a recent AWS update, and the "terraform-provider-aws" has added a new example for the `public-read` ACL.

Here are some related resources:

- https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
- https://github.com/hashicorp/terraform-provider-aws/pull/30513
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl

I have made adjustments to the S3 resources based on these references.

```sh
$ terraform apply

--- snip ---

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

Outputs:

--- snip ---

website_bucket_arn = "arn:aws:s3:::robin-test-dec-17-2019-12345"
website_bucket_domain = "s3-website-us-west-2.amazonaws.com"
website_bucket_name = "robin-test-dec-17-2019-12345"
```

Could you please review?

Additionally, in order for users to successfully follow the tutorial, it seems necessary to update the tutorial. However, I couldn't find the GitHub repository where the tutorial is maintained. Could you please make the necessary updates to the tutorial?

Thank you so much!

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204867093369763

### CODE REVIEW

**Comment by aaronscofield** [comment]
Thanks for this fix, @kakakakakku! Came across the same issue today.

**Comment by snagielEqlipse** [comment]
Resolves (nearly all of) https://github.com/hashicorp/learn-terraform-code-organization/issues/14 as well

**Comment by dangbert** [comment]
Can this PR be merged?

**Comment by vcuenca-rbi** [comment]
This helped me out. Thank you.

**Comment by robin-norwood** [comment]
Sorry for the delay on this one, merged!

**Comment by kakakakakku** [comment]
Thank you 👍

**Pull request merged**
